/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package les_classe;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jozef
 */
public class AjouterCompt extends javax.swing.JFrame {

    /**
     * Creates new form AjouterCompt
     */
    Dashbord dd;
    Connection con ;
    int mouse_y,mouse_x;
    public AjouterCompt(Dashbord d) {
        dd=d;
        con = DbConnection.connect();//connection au base de donnée
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelnom = new javax.swing.JLabel();
        jLabelprenom = new javax.swing.JLabel();
        jLabelcin = new javax.swing.JLabel();
        jLabeltephne = new javax.swing.JLabel();
        jLabelsex = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelmotdepasse = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        jLabelnom.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelnom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnom.setText("Nom :");
        jPanel1.add(jLabelnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 30));

        jLabelprenom.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelprenom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelprenom.setText("Prénom :");
        jPanel1.add(jLabelprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabelcin.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelcin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcin.setText("N°Cin :");
        jPanel1.add(jLabelcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabeltephne.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabeltephne.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltephne.setText("N°Téléphone :");
        jPanel1.add(jLabeltephne, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabelsex.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelsex.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsex.setText("Sexe :");
        jPanel1.add(jLabelsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabelType.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setText("Type :");
        jPanel1.add(jLabelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jLabelmotdepasse.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabelmotdepasse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmotdepasse.setText("Mot De Passe :");
        jPanel1.add(jLabelmotdepasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setMargin(new java.awt.Insets(2, 40, 2, 20));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 220, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 220, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField4.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 220, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("H");
        jRadioButton1.setBorder(null);
        jRadioButton1.setOpaque(false);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 350, -1, 40));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("F");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 40, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Admin", "Employer" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 220, 30));

        jTextField5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField5.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 220, 30));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordField1.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        jLabel2.setVisible(false);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel2.setToolTipText("le nom contient que des lettres !");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 20, 30));

        jLabel3.setVisible(false);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel3.setToolTipText("le prenom contient que des lettres !");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 20, 30));

        jLabel4.setVisible(false);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel4.setToolTipText("le cin contient exactement 8 chiffre et doit etre UNIQUE!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 20, 30));

        jLabel5.setVisible(false);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel5.setToolTipText("le numéro de téléphone contient exactement 8 chiffre !");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 20, 30));

        jLabel6.setVisible(false);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel6.setToolTipText("il faux selectionner le sexe !");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 20, 30));

        jLabel7.setVisible(false);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel7.setToolTipText("il faut selectionner le type du compte !");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 20, 30));

        jLabel8.setVisible(false);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jLabel8.setToolTipText("le mot de passe doit etre contenir au moins 5 caractères !");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 20, 30));

        jLabelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter compt.jpg"))); // NOI18N
        jLabelbackground.setText("jLabel2");
        jPanel1.add(jLabelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 647));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter1.png")));
        
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter2.png")));
    }//GEN-LAST:event_jLabel1MousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dd.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(validation())
        {
            String sexe,type,q;

            if(jRadioButton1.isSelected())
                sexe = "H";
            else
                sexe = "F";
            if(jComboBox1.getSelectedIndex()==1)
                type="admin";
            else
                type="employe";    

            
            Compte cpt = new Compte(jTextField2.getText(),jTextField1.getText(),jTextField4.getText(),jTextField5.getText(),sexe,type,jPasswordField1.getText());
            
            boolean b = cpt.insertion_cpt();
            
            if(b== true)
            {
                dd.setEnabled(true);
                dd.table_compte("");
                this.dispose();
            }else
            {
                jLabel4.setVisible(true);
            }
        }
        
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        
        if(!verifier_chaine(jTextField1.getText()))
            jLabel2.setVisible(true);
        else
            jLabel2.setVisible(false);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if(!verifier_chaine(jTextField4.getText()))
            jLabel3.setVisible(true);
        else
            jLabel3.setVisible(false);
        
        
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if(!verifier_8chiffre(jTextField2.getText()))
            jLabel4.setVisible(true);
        else
            jLabel4.setVisible(false);
        
    }//GEN-LAST:event_jTextField2FocusLost

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        
        if(!verifier_mdp(jPasswordField1.getText()))
            jLabel8.setVisible(true);
        else
            jLabel8.setVisible(false);
        
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(!verifier_8chiffre(jTextField5.getText()))
            jLabel5.setVisible(true);
        else
            jLabel5.setVisible(false);
        
    }//GEN-LAST:event_jTextField5FocusLost

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
       if(jComboBox1.getSelectedIndex()==0)
            jLabel7.setVisible(true);
        else
            jLabel7.setVisible(false);
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        
        int screen_x = evt.getXOnScreen();
        int screen_y = evt.getYOnScreen();
        
        this.setLocation(screen_x-mouse_x,screen_y-mouse_y);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        mouse_x = evt.getX();
        mouse_y = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        dd.setEnabled(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close2.png")));
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close.png")));
        
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini2.png")));
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        // TODO add your handling code here:
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini.png")));
       
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
            {

                evt.consume();
                getToolkit().beep();
             }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
            {

                evt.consume();
                getToolkit().beep();
             }
    }//GEN-LAST:event_jTextField5KeyTyped
   
    boolean validation()
    {
        boolean b=true;
        if(!verifier_chaine(jTextField1.getText()))
        {
            jLabel2.setVisible(true);
            b=false;
        }
        else
            jLabel2.setVisible(false);
        
        if(!verifier_chaine(jTextField4.getText()))
        {
            jLabel3.setVisible(true);
            b=false;
        }
        else
            jLabel3.setVisible(false);
        
        if(!verifier_8chiffre(jTextField2.getText()))
        {
            jLabel4.setVisible(true);
            b=false;
        }
        else
            jLabel4.setVisible(false);
        
        if(!verifier_8chiffre(jTextField5.getText()))
        {
            jLabel5.setVisible(true);
            b=false;
        }
            
        else
            jLabel5.setVisible(false);
        
        if(!verifier_mdp(jPasswordField1.getText()))
        {
            jLabel8.setVisible(true);
            b=false;
        }
        else
            jLabel8.setVisible(false);
        
        if(!jRadioButton2.isSelected()&&!jRadioButton1.isSelected())
        {
            jLabel6.setVisible(true);
            b=false;
        }  
        else
            jLabel6.setVisible(false);
        if(jComboBox1.getSelectedIndex()==0)
        {
            jLabel7.setVisible(true);
            b=false;
        }
        else
            jLabel7.setVisible(false);

        return b;
    }
    boolean verifier_chaine(String s)
    {
        if(s.length()==0)
            return false;
        for(int i = 0;i<s.length();i++)
            if(s.charAt(i)>='a'&&s.charAt(i)<='z'||s.charAt(i)>='A'&&s.charAt(i)<='Z') {
            } else {
                return false;
            }
        return true;
    }
    boolean verifier_8chiffre(String c)
    {
        if(c.length()!=8)
            return false;
        try
        {
            Integer.parseInt(c);
        }catch(NumberFormatException e)
        {
            return false;
        }
        
        return true;       
    }
    boolean verifier_mdp(String m)
    {
        if(m.length()<5)
            return false;
        return true ;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterCompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterCompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterCompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterCompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new AjouterCompt(dd).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelbackground;
    private javax.swing.JLabel jLabelcin;
    private javax.swing.JLabel jLabelmotdepasse;
    private javax.swing.JLabel jLabelnom;
    private javax.swing.JLabel jLabelprenom;
    private javax.swing.JLabel jLabelsex;
    private javax.swing.JLabel jLabeltephne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
