/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package les_classe;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jozef
 */
public class AjouterService extends javax.swing.JFrame {

    /**
     * Creates new form AjouterService
     */
    Dashbord dd;
    int mouse_x;
    int mouse_y;
    Connection con ;
    private boolean client_trouve = false;
    public AjouterService(Dashbord d) {
        con = DbConnection.connect();
        dd=d;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("adresse...");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 170, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 390, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("exemple@exemple.com");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 170, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setText("Thour");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 30));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("Evenement");
        jRadioButton2.setOpaque(false);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton3.setText("Shooting");
        jRadioButton3.setOpaque(false);
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 30));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton4.setText("Mariage");
        jRadioButton4.setOpaque(false);
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Autre type :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 80, 20));

        jTextField4.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 290, 20));

        jTextField5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("nom...");
        jTextField5.setToolTipText("NOM");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField5.setName(""); // NOI18N
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 170, 30));
        jTextField5.getAccessibleContext().setAccessibleName("");

        jTextField16.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField16FocusLost(evt);
            }
        });
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 170, 20));

        jTextField17.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 170, 20));

        jTextField19.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(153, 153, 153));
        jTextField19.setText("cin...");
        jTextField19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField19FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField19FocusLost(evt);
            }
        });
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 170, 30));

        jTextField20.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(153, 153, 153));
        jTextField20.setText("telephone...");
        jTextField20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField20FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField20FocusLost(evt);
            }
        });
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 170, 30));

        jTextField21.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(153, 153, 153));
        jTextField21.setText("prenom...");
        jTextField21.setToolTipText("");
        jTextField21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField21FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField21FocusLost(evt);
            }
        });
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 170, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter1.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 170, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini.png"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel36MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel36MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel35.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel35MouseDragged(evt);
            }
        });
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel35MousePressed(evt);
            }
        });
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        jPanel4.setBackground(new java.awt.Color(34, 45, 49));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("NOM SERVICE :");

        jLabel25.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("TYPE :");

        jLabel30.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TARIF EN DTC :");

        jLabel31.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("AVANCE EN DTC :");

        jLabel33.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CLIENT :");

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("DATE :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 170, 510));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Lieu", "Remarque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 390, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/time-and-date (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 30, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 410, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 410, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/delet_date (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 30, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 20, 20));
        jLabel4.setVisible(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 20, 20));
        jLabel6.setVisible(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 20, 20));
        jLabel7.setVisible(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 20, 20));
        jLabel8.setVisible(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 20, 20));
        jLabel9.setVisible(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 20, 20));
        jLabel10.setVisible(false);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 20, 20));
        jLabel11.setVisible(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 20, 20));
        jLabel12.setVisible(false);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 20, 20));
        jLabel13.setVisible(false);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/faux_Bouton.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 20, 20));
        jLabel14.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter service .jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void jLabel35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MousePressed
        // TODO add your handling code here:
        this.mouse_x = evt.getX();
        this.mouse_y = evt.getY();
    }//GEN-LAST:event_jLabel35MousePressed

    private void jLabel35MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseDragged
        // TODO add your handling code here:
        int screen_x = evt.getXOnScreen();
        int screen_y = evt.getYOnScreen();

        this.setLocation(screen_x-mouse_x, screen_y-mouse_y);
    }//GEN-LAST:event_jLabel35MouseDragged

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        dd.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
        // TODO add your handling code here:
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter1.png")));
        
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/ajouter2.png")));
    }//GEN-LAST:event_jLabel20MousePressed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusLost
        // TODO add your handling code here:
        if(!verifier_chaine(jTextField21.getText()))
        {
            jLabel10.setVisible(true);
        }else
            jLabel10.setVisible(false);
        
        if(this.jTextField21.getText().isEmpty())
        {
            this.jTextField21.setForeground(Color.gray);
            this.jTextField21.setText("prenom...");
        }
    }//GEN-LAST:event_jTextField21FocusLost

    private void jTextField21FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusGained
        // TODO add your handling code here:
        if(this.jTextField21.getText().equals("prenom..."))
        {
            this.jTextField21.setForeground(Color.black);
            this.jTextField21.setText("");
        }
    }//GEN-LAST:event_jTextField21FocusGained

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusLost
        // TODO add your handling code here:
        
        if(!verifier_8chiffre(jTextField20.getText()))
        {
            jLabel11.setVisible(true);
        }else
            jLabel11.setVisible(false);
        if(this.jTextField20.getText().isEmpty())
        {
            this.jTextField20.setForeground(Color.gray);
            this.jTextField20.setText("telephone...");
        }
    }//GEN-LAST:event_jTextField20FocusLost

    private void jTextField20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusGained
        // TODO add your handling code here:
        if(this.jTextField20.getText().equals("telephone..."))
        {
            this.jTextField20.setForeground(Color.black);
            this.jTextField20.setText("");
        }
    }//GEN-LAST:event_jTextField20FocusGained

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField19FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusLost
        // TODO add your handling code here:
        //vider le JtextField
        if(!verifier_8chiffre(jTextField19.getText()))
        {
            jLabel8.setVisible(true);
        }
        else
            jLabel8.setVisible(false);
        if(this.jTextField19.getText().isEmpty())
        {
            this.jTextField19.setForeground(Color.gray);
            this.jTextField19.setText("cin...");
        }
        //tester si le client existe deja
        client_trouve = false;
        
        try {
            String q = "SELECT `cin`, `nom`, `prenom`, `num_tel`, `e_mail`, `adresse` FROM `client` WHERE cin='"+jTextField19.getText()+"'";
            PreparedStatement st = con.prepareStatement(q);
            ResultSet r = st.executeQuery();
            
            while( r.next())
            {
                //JtextField19.setText();
                jTextField5.setText(r.getString("nom"));
                jTextField20.setText(r.getString("num_tel"));
                jTextField21.setText(r.getString("prenom"));
                jTextField1.setText(r.getString("adresse"));
                jTextField3.setText(r.getString("e_mail"));
                
                
                jTextField5.setEnabled(false);
                jTextField20.setEnabled(false);
                jTextField21.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextField3.setEnabled(false);
                
                jTextField5.setDisabledTextColor(new java.awt.Color(52, 73, 94));
                jTextField20.setDisabledTextColor(new java.awt.Color(52, 73, 94));
                jTextField21.setDisabledTextColor(new java.awt.Color(52, 73, 94));
                jTextField1.setDisabledTextColor(new java.awt.Color(52, 73, 94));
                jTextField3.setDisabledTextColor(new java.awt.Color(52, 73, 94));
                
                //FONCTION VERIF DATA
                String c_cin = jTextField19.getText();
                String c_nom = jTextField5.getText() ;
                String c_prenom = jTextField21.getText();
                String c_tel = jTextField20.getText();
                String c_adresse = jTextField1.getText();
                String c_mail = jTextField3.getText();
                //***** client *****   
                //cin 
                if(!verifier_8chiffre(c_cin))
                {
                    jLabel8.setVisible(true);
                }
                else
                    jLabel8.setVisible(false);
                //nom
                if(!verifier_chaine(c_nom))
                {
                    jLabel9.setVisible(true);
                }
                else
                    jLabel9.setVisible(false);
                //prenom
                if(!verifier_chaine(c_prenom))
                {
                    jLabel10.setVisible(true);
                }else
                    jLabel10.setVisible(false);
                //telephone
                if(!verifier_8chiffre(c_tel))
                {
                    jLabel11.setVisible(true);
                }else
                    jLabel11.setVisible(false);
                //adresse
                if(c_adresse.length()<5||c_adresse.equals("adresse..."))
                {
                    jLabel12.setVisible(true);
                }else
                    jLabel12.setVisible(false);
                //email
                if(c_mail.indexOf('@')==-1||c_mail.equals("exemple@exemple.com"))
                {
                    jLabel13.setVisible(true);
                }else if(c_mail.substring(c_mail.indexOf('@'),c_mail.length()).indexOf('.')==-1)
                {
                    jLabel13.setVisible(true);
                }else
            jLabel13.setVisible(false);
            //FIN ICI  */
                client_trouve = true ;
            }
            if(client_trouve == false)
            {
                jTextField5.setText("nom...");
                jTextField20.setText("telephone...");
                jTextField21.setText("prenom...");
                jTextField1.setText("adresse...");
                jTextField3.setText("exemple@exemple.com");
                
                this.jTextField5.setForeground(Color.gray);
                jTextField20.setForeground(Color.gray);
                jTextField21.setForeground(Color.gray);
                jTextField1.setForeground(Color.gray);
                jTextField3.setForeground(Color.gray);
                        
                jTextField5.setEnabled(true);
                jTextField20.setEnabled(true);
                jTextField21.setEnabled(true);
                jTextField1.setEnabled(true);
                jTextField3.setEnabled(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AjouterService.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTextField19FocusLost

    private void jTextField19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusGained
        // TODO add your handling code here:
        if(this.jTextField19.getText().equals("cin..."))
        {
            this.jTextField19.setForeground(Color.black);
            this.jTextField19.setText("");
        }
    }//GEN-LAST:event_jTextField19FocusGained

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(!verifier_chaine(jTextField5.getText()))
        {
            jLabel9.setVisible(true);
        }
        else
            jLabel9.setVisible(false);
        if(this.jTextField5.getText().isEmpty())
        {
            this.jTextField5.setForeground(Color.gray);
            this.jTextField5.setText("nom...");
        }

    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        if(this.jTextField5.getText().equals("nom..."))
        {
            this.jTextField5.setForeground(Color.black);
            this.jTextField5.setText("");
        }

    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:  rgb(236, 240, 241)
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/time-and-date (2).png")));
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/time-and-date (1).png")));
        
        AjouterDate c=new AjouterDate(this);
        c.setVisible(true);
        this.setEnabled(false);

    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/delet_date (2).png")));
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/delet_date (1).png")));
        //DELETE ROW FRom table
        int selected = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //JOptionPane.showMessageDialog(rootPane, selected);
        if(selected!=-1)
            model.removeRow(selected);
        
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(this.jTextField1.getText().equals("adresse..."))
        {
            this.jTextField1.setForeground(Color.black);
            this.jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        
         if(jTextField1.getText().length()<3)
        {
            jLabel12.setVisible(true);
        }else
            jLabel12.setVisible(false);
        if(this.jTextField1.getText().isEmpty())
        {
            this.jTextField1.setForeground(Color.gray);
            this.jTextField1.setText("adresse...");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
        if(this.jTextField3.getText().equals("exemple@exemple.com"))
        {
            this.jTextField3.setForeground(Color.black);
            this.jTextField3.setText("");
        }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        if(jTextField3.getText().length()>0)
        {
            if(jTextField3.getText().indexOf('@')==-1)
            {
                jLabel13.setVisible(true);
            }else if(jTextField3.getText().substring(jTextField3.getText().indexOf('@'),jTextField3.getText().length()).indexOf('.')==-1)
            {
                jLabel13.setVisible(true);
            }else
                jLabel13.setVisible(false);

            if(this.jTextField3.getText().isEmpty())
            {
                this.jTextField3.setForeground(Color.gray);
                this.jTextField3.setText("exemple@exemple.com");
            }
        }
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close2.png")));
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        // TODO add your handling code here:
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/close.png")));
        
    }//GEN-LAST:event_jLabel21MouseReleased

    private void jLabel36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MousePressed
        // TODO add your handling code here:
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini2.png")));
    }//GEN-LAST:event_jLabel36MousePressed

    private void jLabel36MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseReleased
        // TODO add your handling code here:
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/boite/de/production/mini.png")));
       
    }//GEN-LAST:event_jLabel36MouseReleased

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusLost
        // TODO add your handling code here:
        
         if(!verifier_chiffre(jTextField16.getText()))
        {
            jLabel14.setVisible(true);
        }else
            jLabel14.setVisible(false);
        int t;
        try
        {
            t= Integer.parseInt(jTextField16.getText());
            t/=2;
            jTextField17.setText(Integer.toString(t) ) ;
            
        }catch(NumberFormatException e)
        {
            //show label 
        }
        
    }//GEN-LAST:event_jTextField16FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if(!verifier_chaine(jTextField2.getText()))
        {
            jLabel4.setVisible(true);
        }
        else
            jLabel4.setVisible(false);
        
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
            {
                evt.consume();
                getToolkit().beep();
             }
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {
            evt.consume();
            getToolkit().beep();
         }
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {

            evt.consume();
            getToolkit().beep();
         }
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {

            evt.consume();
            getToolkit().beep();
         }
    }//GEN-LAST:event_jTextField20KeyTyped

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        
        if(testData())
        {
            
            String nom = jTextField2.getText();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            String autreType;

            String c_cin = jTextField19.getText();
            String c_nom = jTextField5.getText() ;
            String c_prenom = jTextField21.getText();
            String c_tel = jTextField20.getText();
            String c_adresse = jTextField1.getText();
            String c_mail = jTextField3.getText();
            
            Client cl = new Client(c_nom,c_prenom,c_cin,c_tel,c_mail,c_adresse,"");

            String taarif = jTextField16.getText();
            String reste = jTextField17.getText();
            if(!jRadioButton2.isSelected()&&!jRadioButton1.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected())
                 autreType= jTextField4.getText();
            else if(jRadioButton2.isSelected())
                autreType = "Evenement";
            else if(jRadioButton1.isSelected())
                autreType = "Thour";
            else if(jRadioButton3.isSelected())
                autreType = "Shooting";
            else 
                autreType = "Mariage";
            String num_service ;
            
            
            Service serv = new Service(nom,autreType,taarif,reste,c_cin);
            
            if(serv.insertion_serv(model, client_trouve, cl))
            {
                JOptionPane.showMessageDialog(null, "Ajouter avec succès !!!");
                dd.setEnabled(true);
                dd.table_service_non_termine("");
                dd.table_service_termine("");
                this.dispose();
            }
            
            //****
            
            //model.getValueAt(selected_row,1 )
            
            
        }
    }//GEN-LAST:event_jLabel20MouseClicked


    public DefaultTableModel getTable()
    {
        return (DefaultTableModel)jTable1.getModel();
    }
    private boolean testData()
    {
        boolean ff =true;
        
        String nom = jTextField2.getText();
        String autreType = jTextField4.getText();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
        
        String c_cin = jTextField19.getText();
        String c_nom = jTextField5.getText() ;
        String c_prenom = jTextField21.getText();
        String c_tel = jTextField20.getText();
       
        String c_mail = jTextField3.getText();
        
        String taarif = jTextField16.getText();
        String reste = jTextField17.getText();
        //nom service 
        if(!verifier_chaine(nom))
        {
            jLabel4.setVisible(true);
            ff = false;
        }
        else
            jLabel4.setVisible(false);
        
        //Type service
        if(!jRadioButton2.isSelected()&&!jRadioButton1.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected()&&autreType.length()==0)
        {
            jLabel6.setVisible(true);
            ff = false;
        }
        else
        {
            jLabel6.setVisible(false);
        }
        //date
        if(model.getRowCount()==0)
        {
            jLabel7.setVisible(true);
            ff = false;
        }
        else
            jLabel7.setVisible(false);
        //***** client *****   
        //cin 
        if(!verifier_8chiffre(c_cin))
        {
            jLabel8.setVisible(true);
            ff = false;
        }
        else
            jLabel8.setVisible(false);
        //nom
        if(!verifier_chaine(c_nom))
        {
            jLabel9.setVisible(true);
            ff = false;
        }
        else
            jLabel9.setVisible(false);
        //prenom
        if(!verifier_chaine(c_prenom))
        {
            jLabel10.setVisible(true);
            ff = false;
        }else
            jLabel10.setVisible(false);
        //telephone
        if(!verifier_8chiffre(c_tel))
        {
            jLabel11.setVisible(true);
            ff = false;
        }else
            jLabel11.setVisible(false);
        //adresse
        
         if(jTextField1.getText().length()<3)
        {
            jLabel12.setVisible(true);
        }else
            jLabel12.setVisible(false);
        if(this.jTextField1.getText().isEmpty())
        {
            this.jTextField1.setForeground(Color.gray);
            this.jTextField1.setText("adresse...");
        }
        //email
        if(c_mail.length()>0)
        {
            if(c_mail.indexOf('@')==-1||c_mail.equals("exemple@exemple.com"))
            {
                jLabel13.setVisible(true);
                ff = false;
            }else if(c_mail.substring(c_mail.indexOf('@'),c_mail.length()).indexOf('.')==-1)
            {
                jLabel13.setVisible(true);
                ff = false;
            }else
                jLabel13.setVisible(false);
            
        }
        
        //Taarif
        if(!verifier_chiffre(taarif))
        {
            jLabel14.setVisible(true);
            ff = false;
        }else
            jLabel14.setVisible(false);
            
        return ff;
    }
    
    boolean verifier_chaine(String s)
    {
        if(s.length()==0)
            return false;
        for(int i = 0;i<s.length();i++)
            if(s.charAt(i)>='a'&&s.charAt(i)<='z'||s.charAt(i)>='A'&&s.charAt(i)<='Z') {
            } else {
                return false;
            }
        return true;
    }
    boolean verifier_8chiffre(String c)
    {
        if(c.length()!=8)
            return false;
        try
        {
            Integer.parseInt(c);
        }catch(NumberFormatException e)
        {
            return false;
        }
        
        return true;       
    }
    boolean verifier_chiffre(String c)
    {
        try
        {
            Integer.parseInt(c);
        }catch(NumberFormatException e)
        {
            return false;
        }
        
        return true;    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new AjouterService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
